spring:
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;TRACE_LEVEL_FILE=4
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
    initialization-mode: always
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none

logging:
  level:
    org.springframework.jdbc.datasource: DEBUG
